"""Skills Git source repository models.

These types describe the ``skillsGit`` block stored at the top of
``config.json`` and the request/response payloads for the
``/api/v1/skills/git/*`` routes.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Persisted config types (mirror what we store in config.json)
# ---------------------------------------------------------------------------


# Repo layout types:
# - ``single``: the whole repo is one skill bundle (its root has SKILL.md);
#   it is materialised as ``.cursor/skills/<name>/`` (clone target).
# - ``multi``: the repo contains many skills as subdirectories (each holds
#   ``SKILL.md``); we mirror each subdir into ``.cursor/skills/<subdir>/``.
SkillsGitRepoKind = Literal["single", "multi"]

# Authentication kinds:
# - ``none``: anonymous (public repo over HTTPS).
# - ``token``: HTTPS Personal Access Token; the token value is read from a
#   ``.env`` variable so we never persist it in config.json.
# - ``ssh``: SSH key on disk; the path lives in config.json (private key
#   itself stays under the user's ``~/.ssh`` directory).
SkillsGitAuthKind = Literal["none", "token", "ssh"]


class SkillsGitAuth(BaseModel):
    """Auth descriptor stored on disk; never holds the secret itself."""

    model_config = ConfigDict(extra="forbid")

    kind: SkillsGitAuthKind = "none"
    # ``token`` mode: env var name (e.g. ``GITHUB_TOKEN``) and optional username
    # (defaults to ``oauth2`` / ``x-access-token`` for major hosts).
    token_env: str | None = None
    username: str | None = None
    # ``ssh`` mode: absolute path to a private key file. Optional passphrase is
    # also referenced via env var name for the same reason as ``token_env``.
    ssh_key_path: str | None = None
    ssh_passphrase_env: str | None = None


class SkillsGitRepo(BaseModel):
    """One configured Git source for skills (persisted entry)."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(description="Stable id (UUID-ish, generated by the backend).")
    name: str = Field(description="Human label shown in the UI.")
    url: str = Field(description="Git remote URL (https:// or git@host:org/repo.git).")
    branch: str | None = Field(
        default=None,
        description="Branch / ref to track. ``None`` lets the remote pick its default head.",
    )
    kind: SkillsGitRepoKind = "single"
    # ``single``: target skill folder name (defaults to the sanitized repo name).
    # ``multi``: optional sub-path inside the repo whose subdirectories become
    # individual skills; ``None`` means the repo root.
    target: str | None = None
    auth: SkillsGitAuth = Field(default_factory=SkillsGitAuth)
    auto_update: bool = False
    # Polling interval used when ``auto_update`` is true (minutes).
    interval_minutes: int = Field(default=60, ge=5, le=24 * 60)

    # Last-sync telemetry (updated by the backend after every sync attempt).
    last_sync_at: str | None = None
    last_sync_status: Literal["ok", "error", "pending"] | None = None
    last_sync_message: str | None = None
    last_commit_sha: str | None = None


class SkillsGitConfig(BaseModel):
    """Whole ``skillsGit`` block in ``config.json``."""

    model_config = ConfigDict(extra="forbid")

    repos: list[SkillsGitRepo] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# API request/response shapes (no id / telemetry on inbound bodies)
# ---------------------------------------------------------------------------


class SkillsGitRepoUpsertBody(BaseModel):
    """POST/PUT body when creating or editing a Git source."""

    model_config = ConfigDict(extra="forbid")

    name: str
    url: str
    branch: str | None = None
    kind: SkillsGitRepoKind = "single"
    target: str | None = None
    auth: SkillsGitAuth = Field(default_factory=SkillsGitAuth)
    auto_update: bool = False
    interval_minutes: int = Field(default=60, ge=5, le=24 * 60)


class SkillsGitSyncResult(BaseModel):
    """Per-repo result returned by sync endpoints."""

    model_config = ConfigDict(extra="forbid")

    id: str
    name: str
    status: Literal["ok", "error"]
    message: str
    commit_sha: str | None = None
    synced_skills: list[str] = Field(default_factory=list)
    duration_ms: int | None = None
